<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:t="http://www.tei-c.org/ns/1.0"
    exclude-result-prefixes="xs t"
    
    version="2.0">
    
    <!-- import base conversion style -->
    <xsl:import href="/home/lou/.com.oxygenxml/extensions/v19.0/frameworks/http___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/html/html.xsl"/>
    
    <xsl:output method="html" exclude-result-prefixes="#all" encoding="utf-8" indent="yes"/>
    <xsl:variable name="now" select="current-time()"/>
    <xsl:variable name="today" select="current-date()"/>
    
  
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
                <!--THIS FILE IS GENERATED FROM AN XML MASTER. DO NOT EDIT (5)-->
                <title><xsl:value-of select="//t:titleStmt/t:title[1]"/></title>
                 <meta name="generator" content="Generated by an XSLT stylesheets"/>
                 <link rel="stylesheet" type="text/css" media="screen, projection"
                    href="http://www.w3.org/Talks/Tools/Slidy/show.css"/>
                <link href="http://www.tei-c.org/release/doc/tei-xsl/tei.css" rel="stylesheet" type="text/css"/>
                <script src="http://www.w3.org/Talks/Tools/Slidy/slidy.js" type="text/javascript"/>
                
            </head>
            <body class="simple" id="TOP">
             <xsl:apply-templates select="t:TEI/t:text/t:body"/>   
            </body>
        </html>
    </xsl:template>
    
    
    <xsl:template match="t:body/t:head"/>
    <xsl:template match="t:teiHeader"/>
    <xsl:template match="t:body/t:div/t:head"/>
    
    
    <xsl:template match="t:body/t:div">
        <div class="slide">
            <h2>
                <xsl:value-of select="t:head"/>
            </h2>
            <xsl:apply-templates/>
        </div>
    </xsl:template>
   
</xsl:stylesheet>